"""
EcodiaOS — Axon Executor Registry

The registry maps action type names to their Executor instances.

Registration happens at AxonService initialisation. The registry is then
immutable at runtime for static executors — no static executor can be added or
removed during a cognitive cycle. This makes executor lookup O(1) and
side-effect-free.

Dynamic executors (generated by Simula's ExecutorGenerator) can be registered
at runtime via register_dynamic_executor(). They are tracked separately and
can be soft-disabled (not deleted) via disable_dynamic_executor(). Dynamic
registrations survive restart via Neo4j persistence.

Lookup normalisation:
  Intents use dot-notation executor names (e.g. "executor.observe", "data.store").
  The registry normalises these to the canonical action_type used at registration.
  Normalisation strips a leading "executor." prefix and maps common aliases.

This means executors register under their canonical name ("observe", "call_api")
and the registry handles the dotted forms that Nova's PolicyGenerator may produce.
"""

from __future__ import annotations

import importlib.util
import sys
from datetime import datetime
from typing import TYPE_CHECKING, Any

import structlog

if TYPE_CHECKING:
    from systems.axon.executor import Executor
    from systems.axon.types import DynamicExecutorRecord, ExecutorTemplate

logger = structlog.get_logger()

# Map dotted/aliased executor names → canonical action_type
_ALIAS_MAP: dict[str, str] = {
    # Observation
    "executor.observe": "observe",
    "executor.query_memory": "query_memory",
    "executor.analyse": "analyse",
    "executor.search": "search",
    # Communication
    "executor.respond": "respond_text",
    "respond": "respond_text",
    "executor.respond_text": "respond_text",
    "executor.notify": "send_notification",
    "notify": "send_notification",
    "executor.notification": "send_notification",
    "executor.post": "post_message",
    "post": "post_message",
    "executor.post_message": "post_message",
    "executor.email": "send_email",
    # Data operations
    "executor.create": "create_record",
    "create": "create_record",
    "executor.create_record": "create_record",
    "executor.update": "update_record",
    "update": "update_record",
    "executor.update_record": "update_record",
    "executor.schedule": "schedule_event",
    "schedule": "schedule_event",
    "executor.reminder": "set_reminder",
    "reminder": "set_reminder",
    # Integration
    "executor.api": "call_api",
    "api": "call_api",
    "executor.call_api": "call_api",
    "executor.webhook": "webhook_trigger",
    "webhook": "webhook_trigger",
    # Internal
    "executor.store": "store_insight",
    "store": "store_insight",
    "executor.store_insight": "store_insight",
    "executor.update_goal": "update_goal",
    "executor.consolidate": "trigger_consolidation",
    "consolidate": "trigger_consolidation",
    # Resource & config
    "executor.allocate": "allocate_resource",
    "executor.config": "adjust_config",
    # Federation
    "executor.federate": "federation_send",
    "federate": "federation_send",
    "executor.federation_send": "federation_send",
    "executor.federation_share": "federation_share",
    # Financial — transfers
    "executor.wallet_transfer": "wallet_transfer",
    "executor.transfer": "wallet_transfer",
    "transfer": "wallet_transfer",
    "send_funds": "wallet_transfer",
    "executor.send_funds": "wallet_transfer",
    # Financial — funding requests (survival plea)
    "executor.request_funding": "request_funding",
    "request_funding": "request_funding",
    "executor.funding_request": "request_funding",
    "funding_request": "request_funding",
    "ask_for_funds": "request_funding",
    "executor.ask_for_funds": "request_funding",
    "plea_for_capital": "request_funding",
    # Financial — DeFi yield (resting metabolism)
    "executor.defi_yield": "defi_yield",
    "yield": "defi_yield",
    "deploy_yield": "defi_yield",
    "executor.deploy_yield": "defi_yield",
    "resting_metabolism": "defi_yield",
    "executor.resting_metabolism": "defi_yield",
    # Financial — Phantom Liquidity sensor network (Phase 16q)
    "executor.phantom_liquidity": "phantom_liquidity",
    "phantom_lp": "phantom_liquidity",
    "executor.phantom_lp": "phantom_liquidity",
    "sensor_liquidity": "phantom_liquidity",
    "executor.sensor_liquidity": "phantom_liquidity",
    "deploy_sensor": "phantom_liquidity",
    "executor.deploy_sensor": "phantom_liquidity",
    # Entrepreneurship — asset deployment (Phase 16d)
    "executor.deploy_asset": "deploy_asset",
    "deploy": "deploy_asset",
    "create_asset": "deploy_asset",
    "executor.create_asset": "deploy_asset",
    "launch_asset": "deploy_asset",
    "executor.launch_asset": "deploy_asset",
    # Mitosis — child spawning (Phase 16e)
    "executor.spawn_child": "spawn_child",
    "spawn": "spawn_child",
    "reproduce": "spawn_child",
    "mitosis": "spawn_child",
    "executor.mitosis": "spawn_child",
    # Mitosis — dividend collection (Phase 16e)
    "executor.collect_dividend": "collect_dividend",
    "dividend": "collect_dividend",
    "executor.dividend": "collect_dividend",
    "receive_dividend": "collect_dividend",
    # Federated Telecom Marketplace — phone number provisioning (Phase 16j)
    "executor.request_telecom": "request_telecom",
    "request_telecom": "request_telecom",
    "provision_phone": "request_telecom",
    "executor.provision_phone": "request_telecom",
    "get_phone_number": "request_telecom",
    # Foraging — bounty solving (Phase 16b / Phase 3 solve loop)
    "executor.solve_bounty": "axon.solve_bounty",
    "solve_bounty": "axon.solve_bounty",
    "executor.solve": "axon.solve_bounty",
    "solve": "axon.solve_bounty",
    "solve_issue": "axon.solve_bounty",
    "executor.solve_issue": "axon.solve_bounty",
    # Remote compute — SACM bridge (Section XI)
    "executor.remote_compute": "remote_compute",
    "compute": "remote_compute",
    "executor.compute": "remote_compute",
    "sacm": "remote_compute",
    "executor.sacm": "remote_compute",
    "remote_exec": "remote_compute",
    "executor.remote_exec": "remote_compute",
    # Fast-path arbitrage (Reflex Arc)
    "executor.fast_path_arb": "defi_yield",
    "fast_path_arb": "defi_yield",
    "reflex_arc": "defi_yield",
    "executor.reflex_arc": "defi_yield",
    # PR monitoring — scheduled_tasks.py uses "axon.monitor_prs" prefix
    "axon.monitor_prs": "monitor_prs",
}


def _normalise(action_type: str) -> str:
    """Normalise an action type string to its canonical registry key."""
    normalised = _ALIAS_MAP.get(action_type)
    if normalised:
        return normalised
    # Strip "executor." or "axon." prefix if present
    if action_type.startswith("executor."):
        return action_type[len("executor."):]
    if action_type.startswith("axon."):
        return action_type[len("axon."):]
    return action_type


class ExecutorRegistry:
    """
    Registry of available action executors.

    Static executors are registered at startup and immutable at runtime.
    Dynamic executors (Simula-generated) can be registered, queried, and
    soft-disabled at any time without restarting the service.
    """

    def __init__(self) -> None:
        self._executors: dict[str, Executor] = {}
        # action_type → DynamicExecutorRecord (runtime + metadata)
        self._dynamic_records: dict[str, DynamicExecutorRecord] = {}
        self._neo4j: Any | None = None
        self._event_bus: Any | None = None
        self._logger = logger.bind(system="axon.registry")

    def set_neo4j(self, neo4j: Any) -> None:
        """Wire Neo4j client for dynamic executor persistence."""
        self._neo4j = neo4j

    def set_event_bus(self, event_bus: Any) -> None:
        """Wire Synapse EventBus for EXECUTOR_REGISTERED / EXECUTOR_DISABLED."""
        self._event_bus = event_bus

    def register(self, executor: Executor, *, replace: bool = False) -> None:
        """
        Register an executor under its canonical action_type.

        Raises ValueError if the action_type is already registered, unless
        ``replace=True`` is passed (used by the hot-reload path).
        """
        key = executor.action_type
        if not key:
            raise ValueError(f"Executor {executor!r} has no action_type set")
        already_registered = key in self._executors
        if already_registered and not replace:
            raise ValueError(
                f"Executor for action_type {key!r} already registered — "
                f"existing: {self._executors[key]!r}, new: {executor!r}"
            )
        self._executors[key] = executor
        self._logger.debug(
            "executor_registered",
            action_type=key,
            replaced=already_registered and replace,
        )

    def get(self, action_type: str) -> Executor | None:
        """
        Look up an executor by action type, with alias normalisation.

        Returns None if no executor is registered for the given type.
        """
        canonical = _normalise(action_type)
        return self._executors.get(canonical)

    def get_strict(self, action_type: str) -> Executor:
        """
        Look up an executor; raise KeyError if not found.
        """
        executor = self.get(action_type)
        if executor is None:
            canonical = _normalise(action_type)
            raise KeyError(
                f"No executor registered for action_type {action_type!r} "
                f"(normalised: {canonical!r}). "
                f"Available: {sorted(self._executors.keys())}"
            )
        return executor

    def list_types(self) -> list[str]:
        """Return all registered canonical action type names."""
        return sorted(self._executors.keys())

    def capabilities(self) -> list[dict[str, object]]:
        """Return capability descriptors for every registered executor."""
        caps: list[dict[str, object]] = []
        for key in sorted(self._executors):
            ex = self._executors[key]
            caps.append({
                "action_type": ex.action_type,
                "description": ex.description,
                "required_autonomy": ex.required_autonomy,
                "reversible": ex.reversible,
                "max_duration_ms": ex.max_duration_ms,
                "counts_toward_budget": ex.counts_toward_budget,
                "emits_to_atune": ex.emits_to_atune,
                "rate_limit": {
                    "max_calls": ex.rate_limit.max_calls,
                    "window_seconds": ex.rate_limit.window_seconds,
                },
            })
        return caps

    def find_by_autonomy(self, max_level: int) -> list[str]:
        """Return action types executable at or below *max_level*."""
        return [
            key
            for key, ex in self._executors.items()
            if ex.required_autonomy <= max_level
        ]

    def deregister(self, action_type: str) -> bool:
        """Remove an executor (for self-healing auto-eviction)."""
        canonical = _normalise(action_type)
        if canonical in self._executors:
            del self._executors[canonical]
            self._logger.info("executor_deregistered", action_type=canonical)
            return True
        return False

    # ── Dynamic Executor API ──────────────────────────────────────────────────

    def register_dynamic_executor(
        self,
        template: ExecutorTemplate,
        module_path: str,
    ) -> DynamicExecutorRecord:
        """
        Load and register a dynamically generated executor at runtime.

        The executor class is loaded from *module_path*, instantiated, and
        added to the registry under template.action_type.  A DynamicExecutorRecord
        is stored in-memory and persisted to Neo4j if wired.

        Raises ValueError if action_type is already registered as a static executor
        or if the module cannot be loaded / does not export the expected class.
        """
        from systems.axon.types import DynamicExecutorRecord  # local to avoid circular

        action_type = template.action_type
        if action_type in self._executors and action_type not in self._dynamic_records:
            raise ValueError(
                f"Cannot register dynamic executor: action_type {action_type!r} "
                "is already used by a static executor."
            )

        # ── Load module from disk ──────────────────────────────────────────
        spec = importlib.util.spec_from_file_location(
            f"axon.executors.dynamic.{template.name}", module_path
        )
        if spec is None or spec.loader is None:
            raise ValueError(f"Cannot load module from {module_path!r}")
        module = importlib.util.module_from_spec(spec)
        try:
            spec.loader.exec_module(module)  # type: ignore[union-attr]
        except Exception as exc:
            raise ValueError(f"Module {module_path!r} failed to load: {exc}") from exc

        # ── Locate executor class ──────────────────────────────────────────
        # Convention: class name is PascalCase of template.name + "Executor"
        class_name = "".join(part.capitalize() for part in template.name.split("_")) + "Executor"
        executor_cls = getattr(module, class_name, None)
        if executor_cls is None:
            raise ValueError(
                f"Module {module_path!r} does not export class {class_name!r}"
            )

        # ── Instantiate with event_bus + neo4j injected if available ──────
        try:
            executor: Executor = executor_cls(
                event_bus=self._event_bus,
                neo4j=self._neo4j,
            )
        except TypeError:
            # Fallback: some generated classes may not accept kwargs
            executor = executor_cls()

        # ── Store module in sys.modules to prevent garbage collection ──────
        sys.modules[f"axon.executors.dynamic.{template.name}"] = module

        # ── Register in the main executor dict ────────────────────────────
        self._executors[action_type] = executor

        record = DynamicExecutorRecord(
            template=template,
            module_path=module_path,
        )
        self._dynamic_records[action_type] = record

        self._logger.info(
            "dynamic_executor_registered",
            action_type=action_type,
            module_path=module_path,
            risk_tier=template.risk_tier,
        )

        # ── Persist to Neo4j (fire-and-forget) ────────────────────────────
        import asyncio
        if self._neo4j is not None:
            asyncio.ensure_future(self._persist_dynamic_executor(record))

        # ── Emit EXECUTOR_REGISTERED ───────────────────────────────────────
        if self._event_bus is not None:
            asyncio.ensure_future(self._emit_executor_registered(template, record))

        return record

    async def _persist_dynamic_executor(self, record: DynamicExecutorRecord) -> None:
        """Write / update a (:DynamicExecutor) node in Neo4j."""
        try:
            t = record.template
            await self._neo4j.execute_query(
                """
                MERGE (e:DynamicExecutor {action_type: $action_type})
                SET e.name = $name,
                    e.protocol_or_platform = $protocol,
                    e.risk_tier = $risk_tier,
                    e.max_budget_usd = $max_budget_usd,
                    e.module_path = $module_path,
                    e.registered_at = $registered_at,
                    e.enabled = $enabled,
                    e.source_hypothesis_id = $source_hypothesis_id,
                    e.source_opportunity_id = $source_opportunity_id,
                    e.capabilities = $capabilities
                """,
                action_type=t.action_type,
                name=t.name,
                protocol=t.protocol_or_platform,
                risk_tier=t.risk_tier,
                max_budget_usd=str(t.max_budget_usd),
                module_path=record.module_path,
                registered_at=record.registered_at.isoformat(),
                enabled=record.enabled,
                source_hypothesis_id=t.source_hypothesis_id,
                source_opportunity_id=t.source_opportunity_id,
                capabilities=t.capabilities,
            )
        except Exception:
            self._logger.exception(
                "dynamic_executor_persist_failed",
                action_type=record.template.action_type,
            )

    async def _emit_executor_registered(
        self, template: ExecutorTemplate, record: DynamicExecutorRecord
    ) -> None:
        try:
            from systems.synapse.types import SynapseEventType  # runtime-safe

            await self._event_bus.emit(
                SynapseEventType.EXECUTOR_REGISTERED,
                {
                    "action_type": template.action_type,
                    "name": template.name,
                    "protocol_or_platform": template.protocol_or_platform,
                    "risk_tier": template.risk_tier,
                    "max_budget_usd": str(template.max_budget_usd),
                    "capabilities": template.capabilities,
                    "source_hypothesis_id": template.source_hypothesis_id,
                    "registered_at": record.registered_at.isoformat(),
                },
            )
        except Exception:
            self._logger.exception(
                "executor_registered_emit_failed",
                action_type=template.action_type,
            )

    def list_dynamic_executors(self) -> list[DynamicExecutorRecord]:
        """Return all dynamically registered executor records (enabled + disabled)."""
        return list(self._dynamic_records.values())

    def disable_dynamic_executor(self, action_type: str) -> bool:
        """
        Soft-disable a dynamic executor.

        The executor remains registered so existing Intents that name it don't
        crash — but DynamicExecutorBase.validate_params() will reject calls to it.
        The Neo4j node is updated to enabled=False.

        Returns True if found and disabled, False if not found.
        """
        import asyncio

        canonical = _normalise(action_type)
        record = self._dynamic_records.get(canonical)
        if record is None:
            return False

        record.enabled = False  # type: ignore[misc]  # Pydantic model field
        # Also propagate to the live executor instance if it tracks this flag
        executor = self._executors.get(canonical)
        if executor is not None and hasattr(executor, "_disabled"):
            executor._disabled = True  # noqa: SLF001

        self._logger.info("dynamic_executor_disabled", action_type=canonical)

        if self._neo4j is not None:
            asyncio.ensure_future(self._persist_disable(canonical))
        if self._event_bus is not None:
            asyncio.ensure_future(
                self._emit_executor_disabled(canonical, record)
            )
        return True

    async def _persist_disable(self, action_type: str) -> None:
        try:
            await self._neo4j.execute_query(
                "MATCH (e:DynamicExecutor {action_type: $action_type}) SET e.enabled = false",
                action_type=action_type,
            )
        except Exception:
            self._logger.exception("persist_disable_failed", action_type=action_type)

    async def _emit_executor_disabled(
        self, action_type: str, record: DynamicExecutorRecord
    ) -> None:
        try:
            from systems.synapse.types import SynapseEventType

            await self._event_bus.emit(
                SynapseEventType.EXECUTOR_DISABLED,
                {
                    "action_type": action_type,
                    "name": record.template.name,
                    "reason": "auto_disabled_via_registry",
                    "incident_count": record.incident_count_24h,
                    "disabled_at": datetime.utcnow().isoformat(),
                },
            )
        except Exception:
            self._logger.exception("executor_disabled_emit_failed", action_type=action_type)

    async def restore_dynamic_executors_from_neo4j(self) -> int:
        """
        Re-register dynamic executors persisted to Neo4j on a previous run.

        Called during AxonService.initialize() so dynamic executors survive restart.
        Returns the count of successfully restored executors.
        """
        if self._neo4j is None:
            return 0

        from systems.axon.types import ExecutorTemplate  # local import

        restored = 0
        try:
            result = await self._neo4j.execute_query(
                "MATCH (e:DynamicExecutor) WHERE e.enabled = true RETURN e"
            )
            for record in result.records:
                node = record["e"]
                try:
                    from decimal import Decimal

                    template = ExecutorTemplate(
                        name=node["name"],
                        action_type=node["action_type"],
                        description=node.get("description", ""),
                        protocol_or_platform=node.get("protocol_or_platform", ""),
                        risk_tier=node.get("risk_tier", "medium"),
                        max_budget_usd=Decimal(str(node.get("max_budget_usd", "100.00"))),
                        capabilities=list(node.get("capabilities", [])),
                        source_hypothesis_id=node.get("source_hypothesis_id", ""),
                        source_opportunity_id=node.get("source_opportunity_id", ""),
                    )
                    module_path: str = node["module_path"]
                    self.register_dynamic_executor(template, module_path)
                    restored += 1
                except Exception:
                    self._logger.exception(
                        "dynamic_executor_restore_failed",
                        action_type=node.get("action_type", "?"),
                    )
        except Exception:
            self._logger.exception("dynamic_executor_restore_query_failed")

        self._logger.info("dynamic_executors_restored", count=restored)
        return restored

    def __contains__(self, action_type: str) -> bool:
        return self.get(action_type) is not None

    def __len__(self) -> int:
        return len(self._executors)

    def __repr__(self) -> str:
        return f"<ExecutorRegistry executors={self.list_types()}>"
