"""
EcodiaOS - Episode Outcome Primitives

Canonical type for recording a completed task episode with domain context.
Systems emit DOMAIN_EPISODE_RECORDED Synapse events with this payload so
that BenchmarkService.DomainKPICalculator can accumulate per-domain KPIs.

Usage (any system that handles domain work):
    from primitives.episodes import EpisodeOutcome
    from systems.synapse.types import SynapseEvent, SynapseEventType

    outcome = EpisodeOutcome(
        domain="software_development",
        outcome="success",
        revenue=Decimal("45.00"),
        cost_usd=Decimal("2.50"),
        duration_ms=7_200_000,  # 2 hours
        custom_metrics={"code_quality": 0.88, "deployment_time_hours": 1.2},
    )
    await bus.emit(SynapseEvent(
        event_type=SynapseEventType.DOMAIN_EPISODE_RECORDED,
        source_system="axon",
        data=outcome.model_dump(mode="json"),
    ))

Domain conventions (not enforced - use whatever makes sense per system):
    "software_development"  - Axon / Simula code-delivery tasks
    "art"                   - Voxis / creative generation tasks
    "trading"               - Phantom / market-making tasks
    "yield"                 - Oikos DeFi yield farming
    "bounty_hunting"        - Oikos / Axon bounty completion
    "consulting"            - Nova knowledge-sale episodes
    "generalist"            - Default when domain is unknown
"""

from __future__ import annotations

from datetime import datetime, timezone
from decimal import Decimal
from typing import Any

from pydantic import Field

from primitives.common import EOSBaseModel, utc_now


class EpisodeOutcome(EOSBaseModel):
    """A completed task episode enriched with domain and economic context.

    Emitted as DOMAIN_EPISODE_RECORDED on the Synapse bus so that
    DomainKPICalculator can accumulate per-domain KPIs without any
    direct import dependency on Benchmarks.

    Fields
    ──────
    domain          - Domain identifier string (see module docstring)
    outcome         - 'success' | 'partial' | 'failure'
    revenue         - USD earned from this episode (Decimal, default 0)
    cost_usd        - Compute/resource cost in USD (Decimal, default 0)
    duration_ms     - Wall-clock time in milliseconds
    custom_metrics  - Domain-specific float measurements (averaged by calculator)
    timestamp       - UTC datetime of episode completion (default: now)
    episode_id      - Optional back-reference to Memory episode node
    source_system   - Originating system (e.g. 'axon', 'oikos', 'simula')
    """

    domain: str = "generalist"
    """Domain category for KPI slicing."""

    outcome: str = "failure"
    """'success' | 'partial' | 'failure'"""

    revenue: Decimal = Decimal("0")
    """Revenue generated by this episode in USD."""

    cost_usd: Decimal = Decimal("0")
    """Compute/resource cost in USD."""

    duration_ms: int = 0
    """Wall-clock duration in milliseconds."""

    custom_metrics: dict[str, float] = Field(default_factory=dict)
    """
    Domain-specific measurements.
    Examples by domain:
      software_development: {'code_quality', 'deployment_time_hours', 'test_coverage'}
      art: {'aesthetic_score', 'revision_count', 'client_approval'}
      trading: {'sharpe_ratio', 'max_drawdown', 'win_rate'}
      yield: {'apy', 'slippage_pct'}
      bounty_hunting: {'bounty_usd', 'submission_time_hours'}
    """

    timestamp: datetime = Field(default_factory=utc_now)
    """UTC datetime of episode completion."""

    episode_id: str | None = None
    """Optional ID of the corresponding Memory episode node."""

    source_system: str = "unknown"
    """System that generated this episode (for debugging)."""

    def to_bus_payload(self) -> dict[str, Any]:
        """Serialize for DOMAIN_EPISODE_RECORDED Synapse event payload."""
        return {
            "domain": self.domain,
            "outcome": self.outcome,
            "revenue": str(self.revenue),
            "cost_usd": str(self.cost_usd),
            "duration_ms": self.duration_ms,
            "custom_metrics": self.custom_metrics,
            "timestamp": self.timestamp.isoformat(),
            "episode_id": self.episode_id,
            "source_system": self.source_system,
        }
