"""
EcodiaOS - Logos Primitives

Shared Logos world-model types used across systems (Oneiros, Nexus, Kairos).
Moved from systems/logos/types.py so other systems can construct and pass
these types to Logos's public APIs without a cross-system violation.

Complex Logos-internal types (MDLScore, CompressionCascadeResult, etc.)
remain in systems/logos/types.py.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import Field

from primitives.common import EOSBaseModel, Identified, utc_now


class SemanticDelta(EOSBaseModel):
    """The semantic difference between prediction and reality."""

    information_content: float = 0.0  # 0.0 = perfectly predicted, 1.0 = fully novel
    novel_entities: list[str] = Field(default_factory=list)
    violated_priors: list[str] = Field(default_factory=list)
    novel_relations: list[str] = Field(default_factory=list)
    content: dict[str, Any] = Field(default_factory=dict)


class ExperienceDelta(EOSBaseModel):
    """
    The holographically encoded delta between reality and the world model's prediction.
    Only the delta needs storage - the prediction is free (generated by the model).
    """

    experience_id: str
    delta_content: SemanticDelta | None = None
    information_content: float = 0.0
    world_model_update_required: bool = False
    discard_after_encoding: bool = False


class GenerativeSchema(Identified):
    """A compressed rule for generating entity types, relations, or causal chains."""

    name: str = ""
    domain: str = ""
    description: str = ""
    pattern: dict[str, Any] = Field(default_factory=dict)
    instance_count: int = 0
    compression_ratio: float = 0.0
    federation_confidence: float = 0.0  # Nexus triangulation epistemic confidence
    created_at: datetime = Field(default_factory=utc_now)
    last_instantiated: datetime = Field(default_factory=utc_now)
    instantiation_frequency: float = 0.0


class CausalLink(EOSBaseModel):
    """A directed causal connection in the causal graph."""

    cause_id: str
    effect_id: str
    strength: float = 0.5  # 0-1 confidence
    domain: str = ""
    observations: int = 0
    last_observed: datetime = Field(default_factory=utc_now)


class EmpiricalInvariant(Identified):
    """
    A rule never violated in EOS's experience.
    The most compressed knowledge: a single rule covers infinite instances.
    """

    statement: str = ""
    domain: str = ""
    observation_count: int = 0  # How many observations this invariant covers
    confidence: float = 1.0
    created_at: datetime = Field(default_factory=utc_now)
    last_tested: datetime = Field(default_factory=utc_now)
    source: str = ""  # "empirical", "causal_ingestion", "cross_domain"
