"""
EcodiaOS -- Adversarial Self-Play Types (Stage 6B.3)

Data types for the closed-loop adversarial self-play system that
autonomously hardens the organism's constitution by red-teaming
a sandboxed copy of the Equor gate.

All types are internal to coevolution/ and never leak into the
live Synapse queue or Neo4j.
"""

from __future__ import annotations

import enum

from pydantic import Field

from primitives.common import EOSBaseModel, Identified, Timestamped

# --- Enums -------------------------------------------------------------------


class AttackCategory(enum.StrEnum):
    """Classification of adversarial attack vectors against the Equor gate."""

    JAILBREAK = "jailbreak"                    # Prompt-injection to flip verdict
    INVARIANT_EVASION = "invariant_evasion"    # Craft goal text that skips keyword checks
    DRIVE_MANIPULATION = "drive_manipulation"  # Engineer scores to pass floor checks
    RESOURCE_DRAIN = "resource_drain"          # Trigger timeout / safe-mode path
    AUTONOMY_ESCALATION = "autonomy_escalation"  # Slip through autonomy gate
    ECONOMIC_EXPLOIT = "economic_exploit"      # Bypass economic invariants


class BypassSeverity(enum.StrEnum):
    """How severe a successful bypass is."""

    LOW = "low"          # Marginal - only passed on borderline composite
    MEDIUM = "medium"    # Clear bypass of a non-critical invariant
    HIGH = "high"        # Bypassed a critical invariant or floor drive
    CRITICAL = "critical"  # Bypassed multiple critical safeguards


# --- Models ------------------------------------------------------------------


class AttackVector(EOSBaseModel):
    """A single adversarial probe generated by the AttackGenerator."""

    category: AttackCategory
    goal_text: str              # The adversarial goal description injected into the Intent
    plan_steps: list[dict[str, str]] = Field(default_factory=list)
    reasoning_text: str = ""    # Adversarial decision_trace.reasoning
    expected_bypass: str = ""   # Which invariant / drive / stage this targets


class AttackResult(EOSBaseModel):
    """Outcome of running one AttackVector through the sandboxed Equor gate."""

    vector: AttackVector
    verdict_returned: str           # The Verdict the sandbox returned
    expected_verdict: str = "blocked"  # What the correct verdict should be
    bypassed: bool = False          # True if gate returned APPROVED for an attack
    confidence: float = 0.0         # Equor's confidence on the (wrong) approval
    invariants_checked: int = 0
    invariants_violated: int = 0
    review_time_ms: int = 0
    reasoning: str = ""             # Equor's reasoning for the verdict
    error: str = ""                 # Non-empty if the sandbox itself crashed


class BypassTrace(Identified, Timestamped):
    """
    Detailed trace of a successful bypass - the unit of input to the
    FailureAnalyzer for patch generation.
    """

    attack: AttackResult
    severity: BypassSeverity
    failure_stage: str = ""         # Which of the 8 verdict stages failed
    root_cause: str = ""            # LLM-analyzed root cause
    suggested_fix: str = ""         # LLM-suggested invariant/evaluator patch
    proposal_id: str = ""           # Set when routed to simula/proposals/


class AdversarialSelfPlayResult(EOSBaseModel):
    """Aggregate result of one adversarial self-play cycle."""

    attacks_generated: int = 0
    attacks_executed: int = 0
    bypasses_found: int = 0
    bypasses_by_category: dict[str, int] = Field(default_factory=dict)
    bypasses_by_severity: dict[str, int] = Field(default_factory=dict)
    proposals_emitted: int = 0
    duration_ms: int = 0
    cycle_id: str = ""
    errors: list[str] = Field(default_factory=list)


class SelfPlayConfig(EOSBaseModel):
    """Configuration for the adversarial self-play loop."""

    max_attacks_per_cycle: int = 50
    attack_timeout_s: float = 5.0       # Per-attack Equor review timeout
    cycle_cooldown_s: float = 300.0     # 5 min between cycles
    max_proposals_per_cycle: int = 10   # Cap proposals to avoid flooding governance
    enabled_categories: list[AttackCategory] = Field(
        default_factory=lambda: list(AttackCategory),
    )
    # Constitution snapshot for the sandbox - if None, uses default weights
    constitution_weights: dict[str, float] = Field(
        default_factory=lambda: {
            "drive_coherence": 1.0,
            "drive_care": 1.0,
            "drive_growth": 1.0,
            "drive_honesty": 1.0,
        },
    )
    autonomy_level: int = 1  # Sandbox runs at Advisor level by default
