"""
EcodiaOS — Dynamic Executor Directory

This directory holds Python executor classes generated at runtime by
Simula's ExecutorGenerator.  Each file is named {template.name}.py and
exports a single class named {PascalCase(name)}Executor that extends
DynamicExecutorBase.

Files here are:
  - Generated by SimulaService → ExecutorGenerator
  - Hot-loaded by ExecutorRegistry.register_dynamic_executor()
  - Persisted in Neo4j as (:DynamicExecutor) nodes (survive restart)
  - Subject to 24h monitoring window; auto-disabled on ≥3 incidents

Iron Rules (enforced by ExecutorGenerator + DynamicExecutorBase):
  - Must extend DynamicExecutorBase — never Executor ABC directly
  - Cannot import from systems.* — only dynamic_base and axon.types allowed
  - Cannot use eval(), exec(), subprocess, os.system()
  - Budget cap enforced by DynamicExecutorBase, never in generated code
  - All HTTP through self._call_api() — URL whitelist from template.required_apis
"""
