"""
Fovea — Type Definitions

The fundamental data structures for prediction-error-based attention.
Prediction errors are not scores. They are structured decompositions of how
reality diverged from the world model's expectations.
"""

from __future__ import annotations

import enum
import hashlib
from datetime import datetime  # noqa: TC003 — Pydantic needs runtime access
from typing import Any

from pydantic import Field

from primitives.common import EOSBaseModel, new_id, utc_now

# ---------------------------------------------------------------------------
# Error type taxonomy
# ---------------------------------------------------------------------------


class ErrorType(enum.StrEnum):
    """The six dimensions along which a prediction can fail."""

    CONTENT = "content"       # World model predicted different content
    TEMPORAL = "temporal"     # World model predicted different timing
    MAGNITUDE = "magnitude"   # World model predicted different intensity/scale
    SOURCE = "source"         # World model predicted different origin
    CATEGORY = "category"     # World model predicted a different type entirely
    CAUSAL = "causal"         # World model predicted different causes/effects


class InternalErrorType(enum.StrEnum):
    """Types of self-model prediction errors."""

    CONSTITUTIONAL = "constitutional"   # Drift from drive alignment
    COMPETENCY = "competency"           # Self-model miscalibration
    BEHAVIORAL = "behavioral"           # Inconsistent policy selection
    AFFECTIVE = "affective"             # Unexpected emotional response


class ErrorRoute(enum.StrEnum):
    """Downstream destinations for prediction errors."""

    WORKSPACE = "workspace"     # High salience -> Global Workspace broadcast
    EVO = "evo"                 # Moderate -> Evo hypothesis queue
    LOGOS = "logos"              # Near-everything -> world model update
    KAIROS = "kairos"           # Causal errors -> causal reasoning
    EQUOR = "equor"             # Constitutional drift -> governance
    ONEIROS = "oneiros"         # Unprocessed backlog -> sleep pressure
    THREAD = "thread"           # Behavioral inconsistency -> narrative coherence


# ---------------------------------------------------------------------------
# Default error type weights
# Category errors weighted highest: they imply the world model's fundamental
# ontology is wrong, not just its parameters.
# ---------------------------------------------------------------------------

DEFAULT_ERROR_WEIGHTS: dict[str, float] = {
    ErrorType.CONTENT: 0.20,
    ErrorType.TEMPORAL: 0.10,
    ErrorType.MAGNITUDE: 0.15,
    ErrorType.SOURCE: 0.15,
    ErrorType.CATEGORY: 0.30,
    ErrorType.CAUSAL: 0.10,
}


# ---------------------------------------------------------------------------
# Prediction context — what the world model was asked about
# ---------------------------------------------------------------------------


class PerceptContext(EOSBaseModel):
    """Context extracted from a percept before querying the world model."""

    percept_id: str = ""
    source_system: str = ""
    channel: str = ""
    modality: str = "text"
    context_type: str = ""        # For precision weighting lookups
    recent_percept_ids: list[str] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# Active prediction — what the world model expects
# ---------------------------------------------------------------------------


class ActivePrediction(EOSBaseModel):
    """
    A prediction generated by querying the world model before a percept arrives.

    Not just "what content" but a full distribution over all error dimensions:
    expected content, timing, magnitude, source, category, and causal context.
    """

    prediction_id: str = Field(default_factory=new_id)
    context: PerceptContext = Field(default_factory=PerceptContext)
    timestamp: datetime = Field(default_factory=utc_now)

    # Predictions along each error dimension
    expected_content: list[float] = Field(default_factory=list)      # Embedding
    expected_timing: float = 0.0                                      # Seconds until next
    expected_magnitude: float = 0.5                                   # Intensity [0,1]
    expected_source: str = ""                                         # Expected origin
    expected_category: str = ""                                       # Expected type
    expected_causal_context: dict[str, Any] = Field(default_factory=dict)

    # Confidence in this prediction — low confidence -> low precision weight
    prediction_confidence: float = 0.5


# ---------------------------------------------------------------------------
# Prediction error — the fundamental unit of Fovea output
# ---------------------------------------------------------------------------


class FoveaPredictionError(EOSBaseModel):
    """
    The fundamental unit of Fovea output.

    Not a score. A structured decomposition of how reality diverged from
    the world model's prediction, decomposed by error type with independent
    precision weights per component.

    Salience = sum(component_i * precision_i * learned_weight_i) for i in 1..6
    """

    id: str = Field(default_factory=new_id)
    percept_id: str = ""
    prediction_id: str = ""
    timestamp: datetime = Field(default_factory=utc_now)

    # Error decomposition by type (all [0, 1])
    content_error: float = 0.0
    temporal_error: float = 0.0
    magnitude_error: float = 0.0
    source_error: float = 0.0
    category_error: float = 0.0
    causal_error: float = 0.0

    # Per-component precision weights (learned, independent per dimension)
    component_precisions: dict[str, float] = Field(
        default_factory=lambda: {e.value: 1.0 for e in ErrorType}
    )

    # Learned weights (start at defaults, adjusted by AttentionWeightLearner)
    error_weights: dict[str, float] = Field(
        default_factory=lambda: dict(DEFAULT_ERROR_WEIGHTS)
    )

    # Composite salience — this IS the attention weight
    # sum(component × precision × learned_weight) across all six
    precision_weighted_salience: float = 0.0

    # Habituation
    habituation_level: float = 0.0
    habituated_salience: float = 0.0

    # Routing
    routes: list[str] = Field(default_factory=list)

    def compute_precision_weighted_salience(self) -> None:
        """
        Compute salience as sum of (component * precision * learned_weight)
        across all six error dimensions.
        """
        components = self.get_error_vector()
        total = 0.0
        for dim, error_val in components.items():
            precision = self.component_precisions.get(dim, 1.0)
            weight = self.error_weights.get(dim, 0.0)
            total += error_val * precision * weight
        self.precision_weighted_salience = total

    def compute_routing(self, workspace_threshold: float) -> None:
        """Determine which downstream systems receive this error."""
        self.routes = []
        s = (
            self.habituated_salience
            if self.habituated_salience > 0
            else self.precision_weighted_salience
        )

        if s > workspace_threshold:
            self.routes.append(ErrorRoute.WORKSPACE)
        if s > 0.1:
            self.routes.append(ErrorRoute.EVO)
        if s > 0.05:
            self.routes.append(ErrorRoute.LOGOS)
        # Causal errors always route to Kairos if non-trivial
        if self.causal_error > 0.15:
            self.routes.append(ErrorRoute.KAIROS)

    def get_dominant_error_type(self) -> ErrorType:
        """Return the error type with the highest weighted contribution."""
        components = self.get_error_vector()
        contributions = {
            ErrorType(dim): (
                error_val
                * self.component_precisions.get(dim, 1.0)
                * self.error_weights.get(dim, 0.0)
            )
            for dim, error_val in components.items()
        }
        return max(contributions, key=contributions.get)  # type: ignore[arg-type]

    def get_error_vector(self) -> dict[str, float]:
        """Return all error components as a dict keyed by ErrorType value."""
        return {
            ErrorType.CONTENT: self.content_error,
            ErrorType.TEMPORAL: self.temporal_error,
            ErrorType.MAGNITUDE: self.magnitude_error,
            ErrorType.SOURCE: self.source_error,
            ErrorType.CATEGORY: self.category_error,
            ErrorType.CAUSAL: self.causal_error,
        }

    def get_signature(self) -> str:
        """
        Hash of error type profile + context for habituation tracking.

        Errors with similar profiles in the same context get the same signature,
        allowing the habituation engine to group repeated identical errors.
        """
        dominant = self.get_dominant_error_type().value
        # Bucket error magnitudes to 0.1 precision for grouping
        bucketed = "|".join(
            f"{k}:{round(v, 1)}" for k, v in sorted(self.get_error_vector().items())
        )
        raw = f"{dominant}:{bucketed}"
        return hashlib.sha256(raw.encode()).hexdigest()[:16]


# ---------------------------------------------------------------------------
# Internal prediction error — self-model violations (Phase D, defined here
# for type completeness; handler deferred)
# ---------------------------------------------------------------------------


class InternalPredictionError(FoveaPredictionError):
    """
    A prediction error generated by EOS's self-model, about its own processing.

    Internal prediction errors carry higher base precision because EOS should
    know itself better than it knows anything external.
    """

    internal_error_type: InternalErrorType = InternalErrorType.BEHAVIORAL
    predicted_state: dict[str, Any] = Field(default_factory=dict)
    actual_state: dict[str, Any] = Field(default_factory=dict)

    # Internal errors have much higher base precision
    precision_multiplier: float = 3.0

    def compute_precision_weighted_salience(self) -> None:
        """Override: internal errors amplified by precision multiplier."""
        components = self.get_error_vector()
        total = 0.0
        for dim, error_val in components.items():
            precision = self.component_precisions.get(dim, 1.0)
            weight = self.error_weights.get(dim, 0.0)
            total += error_val * precision * weight
        self.precision_weighted_salience = total * self.precision_multiplier


# ---------------------------------------------------------------------------
# World model update feedback — for weight learning (Phase C, type defined
# here for completeness)
# ---------------------------------------------------------------------------


class WorldModelUpdate(EOSBaseModel):
    """
    Feedback from Logos about how much the world model changed after
    processing a prediction error. Used by AttentionWeightLearner (Phase C).
    """

    prediction_error_id: str = ""
    magnitude: float = 0.0          # How big was the world model update? [0, 1]
    domain: str = ""                 # Which part of the world model changed
    compression_delta: float = 0.0   # Change in world model compression score
    timestamp: datetime = Field(default_factory=utc_now)


# ---------------------------------------------------------------------------
# Fovea health / metrics snapshot
# ---------------------------------------------------------------------------


class FoveaMetrics(EOSBaseModel):
    """Health snapshot for the Fovea system."""

    errors_processed: int = 0
    workspace_ignitions: int = 0
    habituated_count: int = 0
    dishabituated_count: int = 0
    internal_errors_count: int = 0
    mean_salience: float = 0.0
    mean_precision: float = 0.0
    active_predictions: int = 0
    error_weight_profile: dict[str, float] = Field(default_factory=dict)
    habituation_entries: int = 0


class AttentionProfile(EOSBaseModel):
    """
    Current attentional profile snapshot for Alive telemetry.

    Summarises mean error per dimension over the recent error window,
    the dynamic ignition threshold, habituation count, and the highest-
    salience recent error summary string.
    """

    mean_content_error: float = 0.0
    mean_timing_error: float = 0.0
    mean_magnitude_error: float = 0.0
    mean_source_error: float = 0.0
    mean_category_error: float = 0.0
    mean_causal_error: float = 0.0
    current_ignition_threshold: float = 0.0
    habituated_pattern_count: int = 0
    highest_recent_error_summary: str | None = None
