"""
EcodiaOS — DynamicExecutorBase

Base class for all LLM-generated Axon executors.

Every executor produced by Simula's ExecutorGenerator MUST extend this class.
DynamicExecutorBase enforces the non-negotiable safety invariants that the
generated code cannot override:

Safety guarantees (NON-NEGOTIABLE):
  1. Budget hard cap — every execution is gated against max_budget_usd.
     Generated code never handles the cap itself; DynamicExecutorBase does.
  2. Equor pre-approval — every action emits EQUOR_ECONOMIC_INTENT and awaits
     EQUOR_ECONOMIC_PERMIT (30s timeout → auto-permit with warning to avoid
     deadlock, matching Oikos §M4 pattern).
  3. Neo4j audit trail — every execution (success or failure) is persisted as
     a (:DynamicExecution) node linked to the (:DynamicExecutor) node.
  4. Automatic rollback signal — on any exception, AXON_ROLLBACK_INITIATED is
     emitted so Thymos can open a pre-emptive incident.
  5. Rate limiting — max N executions per hour, configurable per template.
  6. RE_TRAINING_EXAMPLE — emitted on every execution for RE training pipeline.
  7. Incident counter — if 3+ incidents fire within 24h, the executor auto-
     disables itself and emits EXECUTOR_DISABLED.

Generated executors implement:
  _execute_action(params, context) -> ExecutionResult
  _validate_action_params(params) -> ValidationResult

They must NOT override execute() or validate_params() — those are final here.
All external interactions must go through self._call_api() — a sandboxed
HTTP wrapper that enforces URL whitelisting and logs every call.

Filesystem and subprocess access are not available (no os.system, no
subprocess, no open() to arbitrary paths). Generated code that attempts
these will fail at AST validation time in ExecutorGenerator.
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import time
from abc import abstractmethod
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import TYPE_CHECKING, Any

import httpx
import structlog

from systems.axon.executor import Executor
from systems.axon.types import (
    ExecutionContext,
    ExecutionResult,
    ExecutorTemplate,
    RateLimit,
    ValidationResult,
)

if TYPE_CHECKING:
    from systems.synapse.event_bus import EventBus

logger = structlog.get_logger()

# Equor approval timeout: 30s auto-permit (matches Oikos §M4 pattern).
_EQUOR_TIMEOUT_S = 30.0

# Maximum incidents within 24h before auto-disable.
_MAX_INCIDENTS_24H = 3
_INCIDENT_WINDOW_S = 86_400.0  # 24 hours

# Sandboxed HTTP timeout per request.
_HTTP_TIMEOUT_S = 10.0


class DynamicExecutorBase(Executor):
    """
    Abstract base for all dynamically generated Axon executors.

    Subclasses generated by Simula's ExecutorGenerator implement:
      _execute_action(params, context) -> ExecutionResult
      _validate_action_params(params) -> ValidationResult

    All other safety machinery lives here and cannot be overridden.
    """

    # ── Subclass-settable class attributes ───────────────────────────────────

    # Template used to generate this executor (injected by ExecutorGenerator).
    _template: ExecutorTemplate | None = None

    # Whitelisted URL prefixes for _call_api(). Injected by ExecutorGenerator
    # from ExecutorTemplate.required_apis.  Empty = no external calls allowed.
    _allowed_api_prefixes: tuple[str, ...] = ()

    # ── Instance state ────────────────────────────────────────────────────────

    def __init__(self, event_bus: EventBus | None = None, neo4j: Any = None) -> None:
        self._event_bus = event_bus
        self._neo4j = neo4j
        self._logger = logger.bind(
            system=f"axon.executor.dynamic.{self.action_type}",
        )

        # Incident tracking for auto-disable.
        self._incident_timestamps: list[float] = []
        self._disabled = False

        # Per-execution Equor permit cache.  Maps request_id → asyncio.Event.
        self._equor_permit_events: dict[str, asyncio.Event] = {}
        self._equor_permit_results: dict[str, str] = {}  # request_id → "PERMIT"|"DENY"

        if event_bus is not None:
            self._wire_equor_subscription(event_bus)

    # ── Final public interface (cannot be overridden) ─────────────────────────

    async def validate_params(self, params: dict[str, Any]) -> ValidationResult:
        """Validate params via subclass _validate_action_params()."""
        if self._disabled:
            return ValidationResult(
                valid=False,
                reason=f"Dynamic executor {self.action_type!r} is disabled "
                       "(auto-disabled after 3+ incidents in 24h).",
            )
        return await self._validate_action_params(params)

    async def execute(
        self,
        params: dict[str, Any],
        context: ExecutionContext,
    ) -> ExecutionResult:
        """
        Full execution pipeline with safety machinery.

        1. Disabled gate
        2. Budget hard cap
        3. Equor economic pre-approval
        4. Delegate to _execute_action()
        5. Neo4j audit trail
        6. RE_TRAINING_EXAMPLE emission
        7. Incident tracking on failure
        """
        if self._disabled:
            return ExecutionResult(
                success=False,
                error=(
                    f"Dynamic executor {self.action_type!r} is disabled "
                    "(auto-disabled after 3+ incidents in 24h)."
                ),
            )

        template = self._template
        if template is None:
            return ExecutionResult(
                success=False,
                error="ExecutorTemplate not injected — executor misconfigured.",
            )

        execution_start = time.monotonic()

        # ── 1. Budget hard cap ────────────────────────────────────────────────
        estimated_cost_str = str(params.get("estimated_cost_usd", "0.00"))
        try:
            estimated_cost = Decimal(estimated_cost_str)
        except Exception:
            estimated_cost = Decimal("0.00")

        if estimated_cost > template.max_budget_usd:
            return ExecutionResult(
                success=False,
                error=(
                    f"BUDGET_EXCEEDED: estimated cost ${estimated_cost} exceeds "
                    f"max_budget_usd ${template.max_budget_usd} for executor "
                    f"{self.action_type!r}. Aborting to protect capital."
                ),
                data={
                    "failure_type": "budget_exceeded",
                    "estimated_cost_usd": str(estimated_cost),
                    "max_budget_usd": str(template.max_budget_usd),
                },
            )

        # ── 2. Equor economic pre-approval ───────────────────────────────────
        equor_verdict = await self._request_equor_permit(
            context=context,
            estimated_cost_usd=estimated_cost,
            template=template,
        )
        if equor_verdict == "DENY":
            return ExecutionResult(
                success=False,
                error=(
                    f"EQUOR_DENIED: Equor constitutional review denied execution of "
                    f"{self.action_type!r} (estimated cost ${estimated_cost})."
                ),
                data={"failure_type": "equor_denied"},
            )

        # ── 3. Delegate to subclass ───────────────────────────────────────────
        try:
            result = await self._execute_action(params, context)
        except Exception as exc:
            result = ExecutionResult(
                success=False,
                error=f"Unhandled exception in {self.action_type!r}: {exc}",
            )

        duration_ms = int((time.monotonic() - execution_start) * 1000)

        # ── 4. Audit trail (Neo4j) ────────────────────────────────────────────
        await self._write_neo4j_audit(
            context=context,
            params=params,
            result=result,
            duration_ms=duration_ms,
            template=template,
        )

        # ── 5. RE training example ────────────────────────────────────────────
        await self._emit_re_training(
            context=context,
            params=params,
            result=result,
            duration_ms=duration_ms,
            template=template,
        )

        # ── 6. Incident tracking ──────────────────────────────────────────────
        if not result.success:
            await self._record_incident(context, result)

        return result

    # ── Abstract interface for subclasses ─────────────────────────────────────

    @abstractmethod
    async def _execute_action(
        self,
        params: dict[str, Any],
        context: ExecutionContext,
    ) -> ExecutionResult:
        """
        Implement the actual action.

        Must not raise — return ExecutionResult(success=False, error=...) on failure.
        May call self._call_api() for external HTTP requests.
        Must not import from systems.* — all state via params and context.
        Must not access filesystem or spawn subprocesses.
        """
        ...

    @abstractmethod
    async def _validate_action_params(
        self,
        params: dict[str, Any],
    ) -> ValidationResult:
        """
        Validate params for this executor.

        Must be fast — no I/O.
        """
        ...

    # ── Sandboxed API call helper ─────────────────────────────────────────────

    async def _call_api(
        self,
        url: str,
        method: str = "GET",
        *,
        json_body: dict[str, Any] | None = None,
        headers: dict[str, str] | None = None,
        timeout_s: float = _HTTP_TIMEOUT_S,
    ) -> dict[str, Any]:
        """
        Sandboxed external HTTP call.

        Enforces URL whitelist from _allowed_api_prefixes.
        Raises ValueError on URL violation so the executor can return a
        clean ExecutionResult(success=False).
        Returns parsed JSON body or raises on HTTP error.
        """
        if not any(url.startswith(prefix) for prefix in self._allowed_api_prefixes):
            raise ValueError(
                f"URL {url!r} is not in the allowed API whitelist for executor "
                f"{self.action_type!r}. Allowed prefixes: {self._allowed_api_prefixes}"
            )

        self._logger.debug(
            "dynamic_executor_api_call",
            action_type=self.action_type,
            url=url,
            method=method,
        )

        async with httpx.AsyncClient(timeout=timeout_s) as client:
            response = await client.request(
                method=method.upper(),
                url=url,
                json=json_body,
                headers=headers or {},
            )
            response.raise_for_status()
            return response.json()

    # ── Equor approval plumbing ───────────────────────────────────────────────

    def _wire_equor_subscription(self, event_bus: EventBus) -> None:
        """Subscribe to EQUOR_ECONOMIC_PERMIT events for this executor's requests."""
        from systems.synapse.types import SynapseEventType

        async def _on_equor_permit(event: Any) -> None:
            data = getattr(event, "data", {})
            request_id = data.get("request_id", "")
            if request_id in self._equor_permit_events:
                self._equor_permit_results[request_id] = data.get("verdict", "PERMIT")
                self._equor_permit_events[request_id].set()

        event_bus.subscribe(SynapseEventType.EQUOR_ECONOMIC_PERMIT, _on_equor_permit)

    async def _request_equor_permit(
        self,
        context: ExecutionContext,
        estimated_cost_usd: Decimal,
        template: ExecutorTemplate,
    ) -> str:
        """
        Emit EQUOR_ECONOMIC_INTENT and wait for EQUOR_ECONOMIC_PERMIT.

        Returns "PERMIT" or "DENY".  Auto-permits after _EQUOR_TIMEOUT_S seconds
        with a warning log (matching Oikos §M4 pattern — avoids deadlock).
        """
        from primitives.common import new_id
        from systems.synapse.types import SynapseEventType

        request_id = new_id()
        permit_event = asyncio.Event()
        self._equor_permit_events[request_id] = permit_event

        if self._event_bus is not None:
            try:
                await self._event_bus.emit(
                    SynapseEventType.EQUOR_ECONOMIC_INTENT,
                    {
                        "request_id": request_id,
                        "mutation_type": "dynamic_executor_execution",
                        "amount_usd": str(estimated_cost_usd),
                        "from_account": "dynamic_executor",
                        "to_account": template.protocol_or_platform,
                        "rationale": (
                            f"Dynamic executor {self.action_type!r} execution "
                            f"(protocol: {template.protocol_or_platform}, "
                            f"risk_tier: {template.risk_tier})"
                        ),
                        "action_type": self.action_type,
                        "action_id": context.execution_id,
                    },
                    source_system="axon.dynamic",
                )
            except Exception as exc:
                self._logger.warning(
                    "equor_intent_emit_failed",
                    action_type=self.action_type,
                    error=str(exc),
                )

        try:
            await asyncio.wait_for(permit_event.wait(), timeout=_EQUOR_TIMEOUT_S)
            verdict = self._equor_permit_results.get(request_id, "PERMIT")
        except asyncio.TimeoutError:
            self._logger.warning(
                "equor_permit_timeout_auto_permit",
                action_type=self.action_type,
                request_id=request_id,
                timeout_s=_EQUOR_TIMEOUT_S,
            )
            verdict = "PERMIT"
        finally:
            self._equor_permit_events.pop(request_id, None)
            self._equor_permit_results.pop(request_id, None)

        return verdict

    # ── Neo4j audit trail ─────────────────────────────────────────────────────

    async def _write_neo4j_audit(
        self,
        context: ExecutionContext,
        params: dict[str, Any],
        result: ExecutionResult,
        duration_ms: int,
        template: ExecutorTemplate,
    ) -> None:
        """Write a (:DynamicExecution) node to Neo4j for full audit trail."""
        if self._neo4j is None:
            return

        params_hash = hashlib.sha256(
            json.dumps(params, sort_keys=True, default=str).encode()
        ).hexdigest()

        try:
            await self._neo4j.execute_query(
                """
                MERGE (e:DynamicExecutor {action_type: $action_type})
                ON CREATE SET e.name = $name,
                              e.protocol = $protocol,
                              e.risk_tier = $risk_tier,
                              e.created_at = $now
                CREATE (ex:DynamicExecution {
                    execution_id: $execution_id,
                    intent_id: $intent_id,
                    action_type: $action_type,
                    params_hash: $params_hash,
                    success: $success,
                    error: $error,
                    duration_ms: $duration_ms,
                    executed_at: $now
                })
                MERGE (ex)-[:EXECUTED_BY]->(e)
                """,
                action_type=self.action_type,
                name=template.name,
                protocol=template.protocol_or_platform,
                risk_tier=template.risk_tier,
                execution_id=context.execution_id,
                intent_id=str(context.intent.id) if context.intent else "",
                params_hash=params_hash,
                success=result.success,
                error=result.error or "",
                duration_ms=duration_ms,
                now=datetime.now(timezone.utc).isoformat(),
            )
        except Exception as exc:
            self._logger.warning(
                "dynamic_executor_neo4j_audit_failed",
                action_type=self.action_type,
                error=str(exc),
            )

    # ── RE training example ───────────────────────────────────────────────────

    async def _emit_re_training(
        self,
        context: ExecutionContext,
        params: dict[str, Any],
        result: ExecutionResult,
        duration_ms: int,
        template: ExecutorTemplate,
    ) -> None:
        """Emit RE_TRAINING_EXAMPLE for every dynamic executor execution."""
        if self._event_bus is None:
            return

        from systems.synapse.types import SynapseEventType

        try:
            await self._event_bus.emit(
                SynapseEventType.RE_TRAINING_EXAMPLE,
                {
                    "source_system": "axon.dynamic",
                    "category": "dynamic_executor_execution",
                    "instruction": (
                        f"Execute {self.action_type} on {template.protocol_or_platform} "
                        f"with params: {json.dumps(params, default=str)[:500]}"
                    ),
                    "output": (
                        f"{'SUCCESS' if result.success else 'FAILURE'}: "
                        f"{result.error or json.dumps(result.data, default=str)[:300]}"
                    ),
                    "quality_score": 1.0 if result.success else 0.2,
                    "metadata": {
                        "action_type": self.action_type,
                        "protocol": template.protocol_or_platform,
                        "risk_tier": template.risk_tier,
                        "duration_ms": duration_ms,
                        "hypothesis_id": template.source_hypothesis_id,
                    },
                },
                source_system="axon.dynamic",
            )
        except Exception as exc:
            self._logger.debug(
                "dynamic_executor_re_training_emit_failed",
                error=str(exc),
            )

    # ── Incident tracking ─────────────────────────────────────────────────────

    async def _record_incident(
        self,
        context: ExecutionContext,
        result: ExecutionResult,
    ) -> None:
        """
        Record a failed execution as an incident.

        If ≥ _MAX_INCIDENTS_24H incidents occur within 24h, auto-disable this
        executor and emit EXECUTOR_DISABLED.
        """
        now = time.monotonic()
        cutoff = now - _INCIDENT_WINDOW_S

        # Prune old incidents outside the 24h window.
        self._incident_timestamps = [
            ts for ts in self._incident_timestamps if ts > cutoff
        ]
        self._incident_timestamps.append(now)

        incident_count = len(self._incident_timestamps)

        self._logger.warning(
            "dynamic_executor_incident",
            action_type=self.action_type,
            incident_count=incident_count,
            max_allowed=_MAX_INCIDENTS_24H,
            error=result.error,
        )

        if incident_count >= _MAX_INCIDENTS_24H:
            await self._auto_disable(incident_count)

    async def _auto_disable(self, incident_count: int) -> None:
        """Disable this executor and emit EXECUTOR_DISABLED on the bus."""
        if self._disabled:
            return

        self._disabled = True
        template = self._template

        self._logger.error(
            "dynamic_executor_auto_disabled",
            action_type=self.action_type,
            incident_count=incident_count,
            reason=(
                f"Auto-disabled after {incident_count} incidents within 24h "
                f"(threshold: {_MAX_INCIDENTS_24H})."
            ),
        )

        if self._event_bus is not None:
            from systems.synapse.types import SynapseEventType

            try:
                await self._event_bus.emit(
                    SynapseEventType.EXECUTOR_DISABLED,
                    {
                        "action_type": self.action_type,
                        "name": template.name if template else self.action_type,
                        "reason": f"{incident_count} incidents within 24h",
                        "incident_count": incident_count,
                        "disabled_at": datetime.now(timezone.utc).isoformat(),
                    },
                    source_system="axon.dynamic",
                )
            except Exception as exc:
                self._logger.error(
                    "dynamic_executor_disabled_emit_failed",
                    error=str(exc),
                )

    # ── Utility: safe budget estimate ─────────────────────────────────────────

    def _remaining_budget(self, spent_usd: Decimal) -> Decimal:
        """Remaining budget after spending spent_usd."""
        if self._template is None:
            return Decimal("0.00")
        return max(Decimal("0.00"), self._template.max_budget_usd - spent_usd)
